services:
  - type: web
    name: christo_Nodejs
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3009
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
